parameters:
#    senegal_api.example.class: Senegal\ApiBundle\Example

services:
#    senegal_api.example:
#        class: %senegal_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
