parameters:
#    nextmoovment_reference.example.class: Nextmoovment\ReferenceBundle\Example

services:
#    nextmoovment_reference.example:
#        class: %nextmoovment_reference.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
